# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('content', '0002_auto_20160129_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(related_name='lesson', to='common.Tag'),
        ),
    ]
